project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_PERSONAL_TOKEN
base_path: .
preserve_hierarchy: true

files:
  - source: /src/Tonarink.App/Strings/en-US/App.resw
    translation: /src/Tonarink.App/Strings/%locale%/App.resw
  - source: /store-listing/en-US/listing.json
    translation: /store-listing/%locale%/listing.json
  - source: /website/content/en-US/**/*.md
    dest: /website/**/%original_file_name%
    translation: /website/content/%locale%/**/%original_file_name%
  - source: /website/locales/en-US.json
    dest: /website/site.json
    translation: /website/locales/%locale%.json
