<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Features>$(Features);runtime-async=on</Features>
    <OutputType>Exe</OutputType>
    <AssemblyName>localsend-dotnet</AssemblyName>
    <RootNamespace>LocalSendDotNet.Cli</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <ProjectReference Include="../LocalSendDotNet.Core/LocalSendDotNet.Core.csproj" />
  </ItemGroup>
</Project>
