<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Features>$(Features);runtime-async=on</Features>
    <IsAotCompatible>true</IsAotCompatible>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <Version>1.1.0</Version>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="System.CommandLine" />
    <ProjectReference Include="../LocalSendDotNet.Core/LocalSendDotNet.Core.csproj" />
    <ProjectReference Include="../Tonarink.Application/Tonarink.Application.csproj" />
    <InternalsVisibleTo Include="Tonarink" />
    <InternalsVisibleTo Include="Tonarink.Cli" />
  </ItemGroup>
</Project>
