<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\LocalSendDotNet.Core\LocalSendDotNet.Core.csproj" />
    <ProjectReference Include="..\Tonarink.Application\Tonarink.Application.csproj" />
  </ItemGroup>

</Project>
